/*
 * THIS FILE IS GENERATED BY D:\PROJ\WATT32S\UTIL\TCC_ERR.EXE. DO NOT EDIT.
 *
 * Watt-32 sys_errlist replaces vendor's sys_errlist
 */

#ifndef __TURBOC__
#error This file is only for use by "__TURBOC__"
#endif

char __syserr36[] = "Operation would block (EWOULDBLOCK)";
char __syserr40[] = "Resource deadlock avoided (EDEADLK)";
char __syserr47[] = "File name too long (ENAMETOOLONG)";
char __syserr49[] = "No locks available (ENOLCK)";
char __syserr51[] = "Function not implemented (ENOSYS)";
char __syserr53[] = "Directory not empty (ENOTEMPTY)";
char __syserr61[] = "Operation now in progress (EINPROGRESS)";
char __syserr62[] = "Operation already in progress (EALREADY)";
char __syserr63[] = "Socket operation on non-socket (ENOTSOCK)";
char __syserr64[] = "Destination address required (EDESTADDRREQ)";
char __syserr65[] = "Message too long (EMSGSIZE)";
char __syserr66[] = "Protocol wrong type for socket (EPROTOTYPE)";
char __syserr67[] = "Protocol option not available (ENOPROTOOPT)";
char __syserr68[] = "Protocol not supported (EPROTONOSUPPORT)";
char __syserr69[] = "Socket type not supported (ESOCKTNOSUPPORT)";
char __syserr70[] = "Operation not supported on socket (EOPNOTSUPP)";
char __syserr71[] = "Protocol family not supported (EPFNOSUPPORT)";
char __syserr72[] = "Address family not supported by protocol (EAFNOSUPPORT)";
char __syserr73[] = "Address already in use (EADDRINUSE)";
char __syserr74[] = "Can't assign requested address (EADDRNOTAVAIL)";
char __syserr75[] = "Network is down (ENETDOWN)";
char __syserr76[] = "Network is unreachable (ENETUNREACH)";
char __syserr77[] = "Network dropped connection on reset (ENETRESET)";
char __syserr78[] = "Software caused connection abort (ECONNABORTED)";
char __syserr79[] = "Connection reset by peer (ECONNRESET)";
char __syserr80[] = "No buffer space available (ENOBUFS)";
char __syserr81[] = "Socket is already connected (EISCONN)";
char __syserr82[] = "Socket is not connected (ENOTCONN)";
char __syserr83[] = "Can't send after socket shutdown (ESHUTDOWN)";
char __syserr84[] = "Connection timed out (ETIMEDOUT)";
char __syserr85[] = "Connection refused (ECONNREFUSED)";
char __syserr86[] = "Host is down (EHOSTDOWN)";
char __syserr87[] = "No route to host (EHOSTUNREACH)";
char __syserr88[] = "Stale NFS file handle (ESTALE)";
char __syserr89[] = "Too many levels of remote in path (EREMOTE)";
char __syserr90[] = "RPC struct is bad (EBADRPC)";
char __syserr91[] = "RPC version wrong (ERPCMISMATCH)";
char __syserr92[] = "RPC prog. not avail (EPROGUNAVAIL)";
char __syserr93[] = "RPC Program version wrong (EPROGMISMATCH)";
char __syserr94[] = "Bad procedure for program (EPROCUNAVAIL)";
char __syserr95[] = "Multibyte/wide character encoding error (EILSEQ)";
char __syserr96[] = "Locking violation (EDEADLOCK)";
char __syserr100[] = "Too many references (ETOOMANYREFS)";
char __syserr101[] = "Too many levels of symbolic links (ELOOP)";
char __syserr102[] = "Too many processes (EPROCLIM)";
char __syserr103[] = "Too many users (EUSERS)";
char __syserr104[] = "Disc quota exceeded (EDQUOT)";
char __syserr105[] = "RVD related disk error (EVDBAD)";
char __syserr106[] = "Out of remote working directory stuctures (ENORMTWD)";

char *SYS_ERRLIST[] = {
    __syserr00,  __syserr01,  __syserr02,  __syserr03,  __syserr04, 
    __syserr05,  __syserr06,  __syserr07,  __syserr08,  __syserr09, 
    __syserr10,  __syserr11,  __syserr12,  __syserr13,  __syserr14, 
    __syserr15,  __syserr16,  __syserr17,  __syserr18,  __syserr19, 
    __syserr20,  __syserr21,  __syserr22,  __syserr23,  __syserr24, 
    __syserr25,  __syserr26,  __syserr27,  __syserr28,  __syserr29, 
    __syserr30,  __syserr31,  __syserr32,  __syserr33,  __syserr34, 
    __syserr35,  __syserr36,  __syserr37,  __syserr38,  __syserr39, 
    __syserr40,  __syserr41,  __syserr42,  __syserr43,  __syserr44, 
    __syserr45,  __syserr46,  __syserr47,  __syserr48,  __syserr49, 
    __syserr50,  __syserr51,  __syserr52,  __syserr53,  __syserr54, 
    __syserr55,  __syserr56,  __syserr57,  __syserr58,  __syserr59, 
    __syserr60,  __syserr61,  __syserr62,  __syserr63,  __syserr64, 
    __syserr65,  __syserr66,  __syserr67,  __syserr68,  __syserr69, 
    __syserr70,  __syserr71,  __syserr72,  __syserr73,  __syserr74, 
    __syserr75,  __syserr76,  __syserr77,  __syserr78,  __syserr79, 
    __syserr80,  __syserr81,  __syserr82,  __syserr83,  __syserr84, 
    __syserr85,  __syserr86,  __syserr87,  __syserr88,  __syserr89, 
    __syserr90,  __syserr91,  __syserr92,  __syserr93,  __syserr94, 
    __syserr95,  __syserr96,  __syserr97,  __syserr98,  __syserr99, 
    __syserr100,  __syserr101,  __syserr102,  __syserr103,  __syserr104, 
    __syserr105,  __syserr106, 
};

