/*
 * THIS FILE IS GENERATED BY D:\PROJ\WATT32S\UTIL\LS_ERR.EXE. DO NOT EDIT.
 *
 * Watt-32 sys_errlist replaces vendor's sys_errlist
 */

#ifndef __CCDL__
#error This file is only for use by "__CCDL__"
#endif

char __syserr51[] = "Operation would block (EWOULDBLOCK)";
char __syserr33[] = "UNIX - not MSDOS (EDOM)";
char __syserr34[] = "Broken pipe (ERANGE)";
char __syserr20[] = "No such device (E2BIG)";
char __syserr05[] = "Invalid memory block address (EACCES)";
char __syserr42[] = "Input/output error (EAGAIN)";
char __syserr06[] = "Invalid environment (EBADF)";
char __syserr44[] = "Resource temporarily unavailable (EBUSY)";
char __syserr24[] = "Cross-device link (ECHILD)";
char __syserr52[] = "Resource deadlock avoided (EDEADLK)";
char __syserr35[] = "Math argument (EEXIST)";
char __syserr14[] = "No such file or director (EFAULT)";
char __syserr27[] = "UNIX - not MSDOS (EFBIG)";
char __syserr39[] = "Operation not permitted (EINTR)";
char __syserr19[] = "Unknown error (EINVAL)";
char __syserr40[] = "UNIX - not MSDOS (EIO)";
char __syserr46[] = "Resource busy (EISDIR)";
char __syserr04[] = "Memory blocks destroyed (EMFILE)";
char __syserr31[] = "Illegal seek (EMLINK)";
char __syserr48[] = "UNIX - not MSDOS (ENAMETOOLONG)";
char __syserr23[] = "Exec format error (ENFILE)";
char __syserr15[] = "Too many open files (ENODEV)";
char __syserr02[] = "File not found (ENOENT)";
char __syserr21[] = "Invalid argument (ENOEXEC)";
char __syserr53[] = "No locks available (ENOLCK)";
char __syserr08[] = "Invalid access code (ENOMEM)";
char __syserr28[] = "UNIX - not MSDOS (ENOSPC)";
char __syserr54[] = "Function not implemented (ENOSYS)";
char __syserr45[] = "UNIX - not MSDOS (ENOTDIR)";
char __syserr55[] = "Directory not empty (ENOTEMPTY)";
char __syserr25[] = "Too many open files (ENOTTY)";
char __syserr41[] = "Interrupted function call (ENXIO)";
char __syserr37[] = "File already exists (EPERM)";
char __syserr32[] = "Read-only file system (EPIPE)";
char __syserr30[] = "No space left on device (EROFS)";
char __syserr29[] = "UNIX - not MSDOS (ESPIPE)";
char __syserr38[] = "Locking violation (ESRCH)";
char __syserr22[] = "Arg list too long (EXDEV)";
char __syserr18[] = "Not enough core (ENMFILE)";
char __syserr56[] = "Operation now in progress (EINPROGRESS)";
char __syserr57[] = "Operation already in progress (EALREADY)";
char __syserr58[] = "Socket operation on non-socket (ENOTSOCK)";
char __syserr59[] = "Destination address required (EDESTADDRREQ)";
char __syserr60[] = "Message too long (EMSGSIZE)";
char __syserr61[] = "Protocol wrong type for socket (EPROTOTYPE)";
char __syserr62[] = "Protocol option not available (ENOPROTOOPT)";
char __syserr63[] = "Protocol not supported (EPROTONOSUPPORT)";
char __syserr64[] = "Socket type not supported (ESOCKTNOSUPPORT)";
char __syserr65[] = "Operation not supported on socket (EOPNOTSUPP)";
char __syserr66[] = "Protocol family not supported (EPFNOSUPPORT)";
char __syserr67[] = "Address family not supported by protocol (EAFNOSUPPORT)";
char __syserr68[] = "Address already in use (EADDRINUSE)";
char __syserr69[] = "Can't assign requested address (EADDRNOTAVAIL)";
char __syserr70[] = "Network is down (ENETDOWN)";
char __syserr71[] = "Network is unreachable (ENETUNREACH)";
char __syserr72[] = "Network dropped connection on reset (ENETRESET)";
char __syserr73[] = "Software caused connection abort (ECONNABORTED)";
char __syserr74[] = "Connection reset by peer (ECONNRESET)";
char __syserr75[] = "No buffer space available (ENOBUFS)";
char __syserr76[] = "Socket is already connected (EISCONN)";
char __syserr77[] = "Socket is not connected (ENOTCONN)";
char __syserr78[] = "Can't send after socket shutdown (ESHUTDOWN)";
char __syserr79[] = "Connection timed out (ETIMEDOUT)";
char __syserr80[] = "Connection refused (ECONNREFUSED)";
char __syserr81[] = "Host is down (EHOSTDOWN)";
char __syserr82[] = "No route to host (EHOSTUNREACH)";
char __syserr83[] = "Stale NFS file handle (ESTALE)";
char __syserr84[] = "Too many levels of remote in path (EREMOTE)";
char __syserr85[] = "RPC struct is bad (EBADRPC)";
char __syserr86[] = "RPC version wrong (ERPCMISMATCH)";
char __syserr87[] = "RPC prog. not avail (EPROGUNAVAIL)";
char __syserr88[] = "RPC Program version wrong (EPROGMISMATCH)";
char __syserr89[] = "Bad procedure for program (EPROCUNAVAIL)";
char __syserr90[] = "Multibyte/wide character encoding error (EILSEQ)";
char __syserr01[] = "Invalid function number (EINVFNC)";
char __syserr03[] = "Path not found (ENOPATH)";
char __syserr07[] = "Invalid format (ECONTR)";
char __syserr09[] = "Invalid data (EINVMEM)";
char __syserr10[] = "Invalid drive specified (EINVENV)";
char __syserr11[] = "Attempt to remove CurDir (EINVFMT)";
char __syserr12[] = "Not same device (EINVACC)";
char __syserr13[] = "No more files (EINVDAT)";
char __syserr36[] = "Result too large (EDEADLOCK)";
char __syserr16[] = "Permission denied (ECURDIR)";
char __syserr17[] = "Bad file number (ENOTSAM)";
char __syserr26[] = "No child process (ETXTBSY)";
char __syserr43[] = "No such device or address (ENOTBLK)";
char __syserr47[] = "UNIX - not MSDOS (EUCLEAN)";
char __syserr91[] = "Too many references (ETOOMANYREFS)";
char __syserr92[] = "Too many levels of symbolic links (ELOOP)";
char __syserr93[] = "Too many processes (EPROCLIM)";
char __syserr94[] = "Too many users (EUSERS)";
char __syserr95[] = "Disc quota exceeded (EDQUOT)";
char __syserr96[] = "RVD related disk error (EVDBAD)";
char __syserr97[] = "Out of remote working directory stuctures (ENORMTWD)";
char __syserr98[] = "Value too large (EOVERFLOW)";

char *SYS_ERRLIST[] = {
    __syserr00,  __syserr01,  __syserr02,  __syserr03,  __syserr04, 
    __syserr05,  __syserr06,  __syserr07,  __syserr08,  __syserr09, 
    __syserr10,  __syserr11,  __syserr12,  __syserr13,  __syserr14, 
    __syserr15,  __syserr16,  __syserr17,  __syserr18,  __syserr19, 
    __syserr20,  __syserr21,  __syserr22,  __syserr23,  __syserr24, 
    __syserr25,  __syserr26,  __syserr27,  __syserr28,  __syserr29, 
    __syserr30,  __syserr31,  __syserr32,  __syserr33,  __syserr34, 
    __syserr35,  __syserr36,  __syserr37,  __syserr38,  __syserr39, 
    __syserr40,  __syserr41,  __syserr42,  __syserr43,  __syserr44, 
    __syserr45,  __syserr46,  __syserr47,  __syserr48,  __syserr00, 
    __syserr00,  __syserr51,  __syserr52,  __syserr53,  __syserr54, 
    __syserr55,  __syserr56,  __syserr57,  __syserr58,  __syserr59, 
    __syserr60,  __syserr61,  __syserr62,  __syserr63,  __syserr64, 
    __syserr65,  __syserr66,  __syserr67,  __syserr68,  __syserr69, 
    __syserr70,  __syserr71,  __syserr72,  __syserr73,  __syserr74, 
    __syserr75,  __syserr76,  __syserr77,  __syserr78,  __syserr79, 
    __syserr80,  __syserr81,  __syserr82,  __syserr83,  __syserr84, 
    __syserr85,  __syserr86,  __syserr87,  __syserr88,  __syserr89, 
    __syserr90,  __syserr91,  __syserr92,  __syserr93,  __syserr94, 
    __syserr95,  __syserr96,  __syserr97,  __syserr98, 
};

