/*
 * THIS FILE WAS GENERATED BY D:\PROJ\WATT32S\UTIL\PO_ERR.EXE. DO NOT EDIT.
 *
 * Watt-32 sys_errlist replaces vendor's sys_errlist
 */

#ifndef __POCC__
#error This file is only for use by "__POCC__"
#endif

char __syserr42[] = "Operation would block (EWOULDBLOCK)";
char __syserr33[] = "domain error (EDOM)";
char __syserr34[] = "range error (ERANGE)";
char __syserr43[] = "Argument list too long (E2BIG)";
char __syserr13[] = "permission denied (EACCES)";
char __syserr11[] = "resource temporarily unavailable (EAGAIN)";
char __syserr09[] = "bad file descriptor (EBADF)";
char __syserr44[] = "Resource busy (EBUSY)";
char __syserr10[] = "no child processes (ECHILD)";
char __syserr36[] = "resource deadlock avoided (EDEADLK)";
char __syserr17[] = "file exists (EEXIST)";
char __syserr45[] = "Bad address (EFAULT)";
char __syserr46[] = "File too large (EFBIG)";
char __syserr47[] = "Interrupted system call (EINTR)";
char __syserr22[] = "invalid argument (EINVAL)";
char __syserr48[] = "Input or output error (EIO)";
char __syserr49[] = "Is a directory (EISDIR)";
char __syserr24[] = "too many open files (EMFILE)";
char __syserr50[] = "Too many links (EMLINK)";
char __syserr51[] = "File name too long (ENAMETOOLONG)";
char __syserr52[] = "Too many open files in system (ENFILE)";
char __syserr53[] = "No such device (ENODEV)";
char __syserr02[] = "no such file or directory (ENOENT)";
char __syserr08[] = "exec format error (ENOEXEC)";
char __syserr54[] = "No locks available (ENOLCK)";
char __syserr12[] = "not enough space (ENOMEM)";
char __syserr28[] = "no space left on device (ENOSPC)";
char __syserr55[] = "Function not implemented (ENOSYS)";
char __syserr56[] = "Not a directory (ENOTDIR)";
char __syserr57[] = "Directory not empty (ENOTEMPTY)";
char __syserr58[] = "Inappropriate I/O control operation (ENOTTY)";
char __syserr59[] = "No such device or address (ENXIO)";
char __syserr60[] = "Operation not permitted (EPERM)";
char __syserr32[] = "broken pipe (EPIPE)";
char __syserr61[] = "Read-only file system (EROFS)";
char __syserr62[] = "Invalid seek (ESPIPE)";
char __syserr63[] = "No such process (ESRCH)";
char __syserr18[] = "error #018 (EXDEV)";
char __syserr64[] = "No more files (ENMFILE)";
char __syserr65[] = "Operation now in progress (EINPROGRESS)";
char __syserr66[] = "Operation already in progress (EALREADY)";
char __syserr67[] = "Socket operation on non-socket (ENOTSOCK)";
char __syserr68[] = "Destination address required (EDESTADDRREQ)";
char __syserr69[] = "Message too long (EMSGSIZE)";
char __syserr70[] = "Protocol wrong type for socket (EPROTOTYPE)";
char __syserr71[] = "Protocol option not available (ENOPROTOOPT)";
char __syserr72[] = "Protocol not supported (EPROTONOSUPPORT)";
char __syserr73[] = "Socket type not supported (ESOCKTNOSUPPORT)";
char __syserr74[] = "Operation not supported on socket (EOPNOTSUPP)";
char __syserr75[] = "Protocol family not supported (EPFNOSUPPORT)";
char __syserr76[] = "Address family not supported by protocol (EAFNOSUPPORT)";
char __syserr77[] = "Address already in use (EADDRINUSE)";
char __syserr78[] = "Can't assign requested address (EADDRNOTAVAIL)";
char __syserr79[] = "Network is down (ENETDOWN)";
char __syserr80[] = "Network is unreachable (ENETUNREACH)";
char __syserr81[] = "Network dropped connection on reset (ENETRESET)";
char __syserr82[] = "Software caused connection abort (ECONNABORTED)";
char __syserr83[] = "Connection reset by peer (ECONNRESET)";
char __syserr84[] = "No buffer space available (ENOBUFS)";
char __syserr85[] = "Socket is already connected (EISCONN)";
char __syserr86[] = "Socket is not connected (ENOTCONN)";
char __syserr87[] = "Can't send after socket shutdown (ESHUTDOWN)";
char __syserr88[] = "Connection timed out (ETIMEDOUT)";
char __syserr89[] = "Connection refused (ECONNREFUSED)";
char __syserr90[] = "Host is down (EHOSTDOWN)";
char __syserr91[] = "No route to host (EHOSTUNREACH)";
char __syserr92[] = "Stale NFS file handle (ESTALE)";
char __syserr93[] = "Too many levels of remote in path (EREMOTE)";
char __syserr94[] = "RPC struct is bad (EBADRPC)";
char __syserr95[] = "RPC version wrong (ERPCMISMATCH)";
char __syserr96[] = "RPC prog. not avail (EPROGUNAVAIL)";
char __syserr97[] = "RPC Program version wrong (EPROGMISMATCH)";
char __syserr98[] = "Bad procedure for program (EPROCUNAVAIL)";
char __syserr99[] = "Invalid function number (EINVFNC)";
char __syserr100[] = "Path not found (ENOPATH)";
char __syserr101[] = "Memory area destroyed (ECONTR)";
char __syserr102[] = "Invalid memory block address (EINVMEM)";
char __syserr103[] = "Invalid environment (EINVENV)";
char __syserr104[] = "Invalid format (EINVFMT)";
char __syserr105[] = "Invalid access code (EINVACC)";
char __syserr106[] = "Invalid data (EINVDAT)";
char __syserr107[] = "Locking violation (EDEADLOCK)";
char __syserr108[] = "Attempt to remove current directory (ECURDIR)";
char __syserr109[] = "Not same device (ENOTSAM)";
char __syserr110[] = "Text file busy (ETXTBSY)";
char __syserr111[] = "Block device required (ENOTBLK)";
char __syserr112[] = "Structure needs cleaning (EUCLEAN)";
char __syserr113[] = "Too many references (ETOOMANYREFS)";
char __syserr114[] = "Too many levels of symbolic links (ELOOP)";
char __syserr115[] = "Too many processes (EPROCLIM)";
char __syserr116[] = "Too many users (EUSERS)";
char __syserr117[] = "Disc quota exceeded (EDQUOT)";
char __syserr118[] = "RVD related disk error (EVDBAD)";
char __syserr119[] = "Out of remote working directory stuctures (ENORMTWD)";
char __syserr120[] = "Value too large (EOVERFLOW)";

char *SYS_ERRLIST[] = {
    __syserr00,  __syserr00,  __syserr02,  __syserr00,  __syserr00, 
    __syserr00,  __syserr00,  __syserr00,  __syserr08,  __syserr09, 
    __syserr10,  __syserr11,  __syserr12,  __syserr13,  __syserr00, 
    __syserr00,  __syserr00,  __syserr17,  __syserr18,  __syserr00, 
    __syserr00,  __syserr00,  __syserr22,  __syserr00,  __syserr24, 
    __syserr00,  __syserr00,  __syserr00,  __syserr28,  __syserr00, 
    __syserr00,  __syserr00,  __syserr32,  __syserr33,  __syserr34, 
    __syserr00,  __syserr36,  __syserr00,  __syserr00,  __syserr00, 
    __syserr00,  __syserr00,  __syserr42,  __syserr43,  __syserr44, 
    __syserr45,  __syserr46,  __syserr47,  __syserr48,  __syserr49, 
    __syserr50,  __syserr51,  __syserr52,  __syserr53,  __syserr54, 
    __syserr55,  __syserr56,  __syserr57,  __syserr58,  __syserr59, 
    __syserr60,  __syserr61,  __syserr62,  __syserr63,  __syserr64, 
    __syserr65,  __syserr66,  __syserr67,  __syserr68,  __syserr69, 
    __syserr70,  __syserr71,  __syserr72,  __syserr73,  __syserr74, 
    __syserr75,  __syserr76,  __syserr77,  __syserr78,  __syserr79, 
    __syserr80,  __syserr81,  __syserr82,  __syserr83,  __syserr84, 
    __syserr85,  __syserr86,  __syserr87,  __syserr88,  __syserr89, 
    __syserr90,  __syserr91,  __syserr92,  __syserr93,  __syserr94, 
    __syserr95,  __syserr96,  __syserr97,  __syserr98,  __syserr99, 
    __syserr100,  __syserr101,  __syserr102,  __syserr103,  __syserr104, 
    __syserr105,  __syserr106,  __syserr107,  __syserr108,  __syserr109, 
    __syserr110,  __syserr111,  __syserr112,  __syserr113,  __syserr114, 
    __syserr115,  __syserr116,  __syserr117,  __syserr118,  __syserr119, 
    __syserr120, 
};

